### ISSUE TITLE
[Bug]: Preview external pages inside hover editor renders surfing preview behind hover editor window

### ISSUE THREAD

**Issue by oscaromsn** [PKM-er/Obsidian-Surfing#243]
### Bug Description

When hover the mouse cursor on an external link inside a hover editor window, the preview opens behind the hover editor window, as the screenshot sent — where the expected behavior would be the twitter preview appears on front of hover editor window.

### Relevant Screenshot

![image](https://github.com/PKM-er/Obsidian-Surfing/assets/29803184/9ed6dcf9-512e-4b8f-a2e7-5d3f5824214d)

### Obsidian Version

Version 1.5.12 (Installer 1.5.12)

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
It's weird. Will be fixed

**Comment by Quorafind** [comment]
Fixed already.

**Comment by oscaromsn** [comment]
The problem still remains here:

![image](https://github.com/PKM-er/Obsidian-Surfing/assets/29803184/c1c5ad15-3be7-4d52-b593-380c75c53ba9)


Tested on the Obsidian Sandbox vault, based on the following version:

```
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 23.4.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: Hover Editor v0.11.19
		2: Surfing v0.9.11
```

**Comment by Quorafind** [comment]
Will look into this issue soon
